controllers/OrderController.php
<?php

namespace app\controllers;

use app\models\Autoapprove;
use app\models\Autopost;
use app\models\Autoredirect;
use app\models\Cancel;
use app\models\Paypal;
use app\models\Rating;
use app\models\Reject;
use app\models\Revision;
use app\models\Uploaded;
use app\models\User;
use app\models\Wallet;
use \app\components\Notification;
use Yii;
use app\models\Message;
use app\models\MessageSearch;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Rest\ApiContext;
use app\models\File;
use app\models\Uniqueid;
use yii\helpers\FileHelper;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use app\models\Service;
use app\models\Type;
use app\models\Level;
use app\models\Pages;
use app\models\Urgency;
use app\models\Spacing;
use app\models\Order;
use app\models\OrderSearch;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    public $layout = 'order';


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [
                    'create', 'index', 'cancel', 'update', 'attached', 'file-delete', 'file-upload',
                    'send-message', 'messages', 'image-upload', 'file-view', 'image-delete', 'cancel',
                    'pending', 'active', 'revision', 'editing', 'completed', 'rejected', 'download-review',
                    'rating', 'disputed', 'view', 'available', 'approved', 'reserve', 'message-count',
                    'order-revision', 'order-approve', 'order-reject'
                ],
                'rules' => [
                    [
                        'actions' => [
                            'create', 'index', 'cancel', 'update', 'attached', 'file-delete', 'file-upload',
                            'send-message', 'messages', 'image-upload', 'file-view', 'image-delete', 'cancel', 'view',
                            'pending', 'active', 'revision', 'editing', 'completed', 'rejected', 'disputed',
                            'download-review', 'rating', 'approved', 'available', 'reserve', 'message-count',
                            'order-revision', 'order-approve', 'order-reject'
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPending()
    {
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['paid' => 0]);
        $dataProvider->query->andFilterWhere(['cancelled' => 0]);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('pending', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionAvailable()
    {
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['available' => 1]);
        $dataProvider->query->andFilterWhere(['cancelled' => 0]);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('available', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionActive()
    {
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['active' => 1]);
        $dataProvider->query->andFilterWhere(['cancelled' => 0]);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('active', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCancelled()
    {
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['cancelled' => 1]);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('cancelled', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionRevision()
    {
        Yii::$app->view->params['logo'] = User::getSiteLogo();
        Yii::$app->view->params['name'] = User::getSiteName();
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['revision' => 1]);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('revision', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionEditing()
    {
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['editing' => 1]);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('editing', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCompleted()
    {
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['completed' => 1]);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('completed', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionApproved()
    {
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['approved' => 1]);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('approved', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionRejected()
    {
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['rejected' => 1]);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('rejected', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDisputed()
    {
        Order::getLogoNameBalance();
        Order::getOrdersCount();
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['disputed' => 1]);
        $dataProvider->query->andFilterWhere(['created_by' => Yii::$app->user->id]);
        return $this->render('disputed', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSendMessage()
    {
        Yii::$app->view->params['logo'] = User::getSiteLogo();
        Yii::$app->view->params['name'] = User::getSiteName();
        Order::getOrdersCount();
        $command1 = Yii::$app->db->createCommand('SELECT SUM(deposit) FROM wallet WHERE customer_id =' . Yii::$app->user->id . '');
        $command2 = Yii::$app->db->createCommand('SELECT SUM(withdraw) FROM wallet WHERE customer_id =' . Yii::$app->user->id . '');
        $totaldeposit = $command1->queryScalar();
        $totalwithdrawal = $command2->queryScalar();
        $balance = $totaldeposit - $totalwithdrawal;
        Yii::$app->view->params['balance'] = $balance;
        $model = new Message();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('send-message', [
                'model' => $model,
            ]);
        }
    }

    public function actionReserve($oid)
    {

views/order/_approved.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\OrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-search">

    <?php $form = \kartik\form\ActiveForm::begin([
        'action' => ['approved'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>



    <?= $form->field($model, 'global', [
        'addon' => [
            'append' => [
                'content' => Html::submitButton('Search', ['class'=>'btn btn-primary']),
                'asButton' => true
            ]
        ]
    ])->label(false);?>
    <?php //echo $form->field($model, 'ordernumber') ?>
    <?php //echo $form->field($model, 'created_by') ?>
    <?php //echo $form->field($model, 'service_id') ?>
    <?php //echo $form->field($model, 'written_by') ?>
    <?php //echo $form->field($model, 'edited_by') ?>
    <?php //echo $form->field($model, 'type_id') ?>

    <?php //echo $form->field($model, 'urgency_id') ?>

    <?php  // echo $form->field($model, 'spacing_id') ?>

    <?php // echo $form->field($model, 'pages_id') ?>

    <?php // echo $form->field($model, 'level_id') ?>

    <?php // echo $form->field($model, 'subject_id') ?>

    <?php // echo $form->field($model, 'style_id') ?>

    <?php // echo $form->field($model, 'sources_id') ?>

    <?php // echo $form->field($model, 'language_id') ?>

    <?php // echo $form->field($model, 'pagesummary') ?>

    <?php // echo $form->field($model, 'plagreport') ?>

    <?php // echo $form->field($model, 'initialdraft') ?>

    <?php // echo $form->field($model, 'topic') ?>

    <?php // echo $form->field($model, 'instructions') ?>

    <?php // echo $form->field($model, 'qualitycheck') ?>

    <?php // echo $form->field($model, 'topwriter') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'promocode') ?>

    <?php // echo $form->field($model, 'files') ?>

    <?php // echo $form->field($model, 'created_at') ?>
    <?php // echo $form->field($model, 'amount') ?>

    <?php \kartik\form\ActiveForm::end(); ?>

</div>

views/order/_editing.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\OrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-search">

    <?php $form = \kartik\form\ActiveForm::begin([
        'action' => ['editing'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>



    <?= $form->field($model, 'global', [
        'addon' => [
            'append' => [
                'content' => Html::submitButton('Search', ['class'=>'btn btn-primary']),
                'asButton' => true
            ]
        ]
    ])->label(false);?>
    <?php //echo $form->field($model, 'ordernumber') ?>
    <?php //echo $form->field($model, 'created_by') ?>
    <?php //echo $form->field($model, 'service_id') ?>
    <?php //echo $form->field($model, 'written_by') ?>
    <?php //echo $form->field($model, 'edited_by') ?>
    <?php //echo $form->field($model, 'type_id') ?>

    <?php //echo $form->field($model, 'urgency_id') ?>

    <?php  // echo $form->field($model, 'spacing_id') ?>

    <?php // echo $form->field($model, 'pages_id') ?>

    <?php // echo $form->field($model, 'level_id') ?>

    <?php // echo $form->field($model, 'subject_id') ?>

    <?php // echo $form->field($model, 'style_id') ?>

    <?php // echo $form->field($model, 'sources_id') ?>

    <?php // echo $form->field($model, 'language_id') ?>

    <?php // echo $form->field($model, 'pagesummary') ?>

    <?php // echo $form->field($model, 'plagreport') ?>

    <?php // echo $form->field($model, 'initialdraft') ?>

    <?php // echo $form->field($model, 'topic') ?>

    <?php // echo $form->field($model, 'instructions') ?>

    <?php // echo $form->field($model, 'qualitycheck') ?>

    <?php // echo $form->field($model, 'topwriter') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'promocode') ?>

    <?php // echo $form->field($model, 'files') ?>

    <?php // echo $form->field($model, 'created_at') ?>
    <?php // echo $form->field($model, 'amount') ?>

    <?php \kartik\form\ActiveForm::end(); ?>

</div>

views/order/_file.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $file app\models\File */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="file-form">
    <?php $form = ActiveForm::begin([
        'options'=>['enctype'=>'multipart/form-data'],
        'action'=>\yii\helpers\Url::to(['/order/file-upload','id'=>$id]),
    ]);?>

    <?= $form->field($file, 'attached[]')->widget(\kartik\file\FileInput::classname(), [
        'options' => ['multiple' => true],
        'name' => 'file[]',
        'pluginOptions' => ['previewFileType' => 'any',
            'showPreview' => false,
//            'theme'=> "explorer",
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => true,
            'hideThumbnailContent'=>'true',
             'browseLabel' => 'Browse Files',
            'browseClass' => 'btn btn-success',
            'uploadClass' => 'btn btn-info',
            'removeClass' => 'btn btn-danger',
            'removeIcon' => '<i class="glyphicon glyphicon-trash"></i> ',
            'maxFileCount' => 25]
    ])->label(false);?>
    <?php ActiveForm::end(); ?>
</div>

views/order/_msg.php
<?php
foreach ($order_messages as $order_message) {
    //get the time from the db in UTC and convert it client timezone
    $startTime = new \DateTime(''.$order_message->created_at.'', new \DateTimeZone('UTC'));
    $startTime->setTimezone(new \DateTimeZone('Africa/Nairobi'));
    $ptime = $startTime->format("M d, Y H:i");
    echo '<div class="mymessage row" style="height: auto; padding: 5px 10px 5px 10px">';
    if ($order_message->sender_id != Yii::$app->user->id){
        echo '<div  class="col-md-7" style="text-align: left; border-radius: 5px; background-color: #ECEFF4">';
        echo '<div>'.$order_message->message.'</div>';
        echo '<div style="text-decoration: underline"><span style="font-style: italic; font-size: small">'.$ptime.'</span></div>';
        echo '</div>';
    }else{
        echo '<div  class="col-md-7 col-md-push-5" style="border-radius: 5px; background-color: #e2e9e4">';
        echo '<div style="text-align: left">'.$order_message->message.'</div>';
        echo '<div style="text-decoration: underline; text-align: left"><span style="font-style: italic; font-size: small">'.$ptime.'</span></div>';
        echo '</div>';
    }
    echo '</div>';
}
?>

views/order/_ordertabs.php
<?php
/**
 * Created by PhpStorm.
 * User: gits
 * Date: 1/15/18
 * Time: 1:03 PM
 */
$myscript = <<< JS
function openCity(evt, cityName) {
    // Declare all variables
    var i, tabcontent, tablinks;

    // Get all elements with class="tabcontent" and hide them
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }

    // Get all elements with class="tablinks" and remove the class "active"
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    // Show the current tab, and add an "active" class to the button that opened the tab
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
}
JS;
$this->registerJs($myscript);
?>
<div class="row tabs">
    <ul class="order-details-menu" style="height: 40px; list-style-type: none; background-color: midnightblue; margin-bottom: 20px; line-height: 40px; vertical-align: middle">
        <li class="<?=$tabactive ?>" style="display: inline-block;"><a href="<?= \yii\helpers\Url::to(['order/view',
            'oid'=>$model->ordernumber])?>"><strong>Order details</strong></a></li>
       <li class="<?=$tab2active?>" style="display: inline-block; "> <a href="<?= \yii\helpers\Url::to(['order/attached',
            'oid'=>$model->ordernumber])?>"><strong>Order Files</strong></a></li>
        <li class="<?=$tab3active?>" style="display: inline-block;"><a href="<?= \yii\helpers\Url::to(['order/messages',
            'oid'=>$model->ordernumber])?>"><strong>Messages</strong></a></li>
    </ul>
</div>
<!--<!-- Tab links -->
<!--<div class="tab">-->
<!--    <button class="tablinks" onclick="openCity(event, 'London')">London</button>-->
<!--    <button class="tablinks" onclick="openCity(event, 'Paris')">Paris</button>-->
<!--    <button class="tablinks" onclick="openCity(event, 'Tokyo')">Tokyo</button>-->
<!--</div>-->
<!---->
<!--<!-- Tab content -->
<!--<div id="London" class="tabcontent">-->
<!--    <h3>London</h3>-->
<!--    <p>London is the capital city of England.</p>-->
<!--</div>-->
<!---->
<!--<div id="Paris" class="tabcontent">-->
<!--    <h3>Paris</h3>-->
<!--    <p>Paris is the capital of France.</p>-->
<!--</div>-->
<!---->
<!--<div id="Tokyo" class="tabcontent">-->
<!--    <h3>Tokyo</h3>-->
<!--    <p>Tokyo is the capital of Japan.</p>-->
<!--</div>-->

views/order/_viewrevision.php
<?php
/**
 * Created by PhpStorm.
 * User: gits
 * Date: 2/27/18
 * Time: 3:05 PM
 */
?>
<tr>
    <td></td>
    <td><span><?= $order_revision->instructions ?></span></td>
    <?php
    $startTime = new \DateTime(''.$order_revision->created_at.'', new \DateTimeZone('UTC'));
    $startTime->setTimezone(new \DateTimeZone(Yii::$app->timezone->name));
    $revtime = $startTime->format("M d, Y g:i a");
    ?>
    <td><span><?= $revtime ?></span></td>
</tr>

views/order/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Create Order';
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="myorder">
        <h2>Place Order</h2>
        <hr>
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>

    </div>

views/order/pending.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Orders Pending Payment';
$this->params['breadcrumbs'][] = $this->title;
//$deadline = <<< JS
//var displayMoment = document.getElementById('deadline-date');
/*var theMoment = moment("<?php echo $model->deadline; ?>", "YYYY-MM-DD HH-mm-ss").fromNow();*/
//
//var now = moment();
/*const exp = moment("<?php echo $model->deadline; ?>", "YYYY-MM-DD HH-mm-ss");*/
//days = exp.diff(now, 'days');
//hours = exp.subtract(days, 'days').diff(now, 'hours');
//minutes = exp.subtract(hours, 'hours').diff(now, 'minutes');
//displayMoment.innerHTML = days+' days, '+hours+' hours, '+minutes+' minutes';
//JS;
//$this->registerJs($deadline);
?>
<div class="myorder" style="margin-left: -10px">
    <h1><?= Html::encode($this->title) ?></h1>
    <hr>
    <div class="row">
        <div class="hidden-lg hidden-md hidden-sm col-xs-4">
            <?php  echo '<div class="dropdown">
                              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Menu
                              <span class="caret"></span></button>
                              <ul class="dropdown-menu">
                                <li><a href="'.Yii::$app->request->baseUrl.'/order/index"><i class="fa fa-dashboard" aria-hidden="true"></i> Dashboard</a></li>
                                <li><a href="'.Yii::$app->request->baseUrl.'/order/create"><i class="fa fa-plus " aria-hidden="true"></i> Place Order</a></li>
                                <li class="active"><a href="'.Yii::$app->request->baseUrl.'/order/pending"><i class="fa fa-list " aria-hidden="true"></i> Pending ('.$this->params['pending_count'].')</a></li>
                                 <li><a href="'.Yii::$app->request->baseUrl.'/order/available"><i class="fa fa-clock-o" aria-hidden="true"></i> Waiting to be assigned ('.$this->params['available_count'].')</a></li>
                                <li><a href="'.Yii::$app->request->baseUrl.'/order/active"><i class="fa fa-spinner fa-spin" aria-hidden="true"></i> In Progress ('.$this->params['active_count'].')</a></li>
                                <li><a href="'.Yii::$app->request->baseUrl.'/order/cancelled"><i class="fa fa-close" aria-hidden="true"></i> Cancelled ('.$this->params['cancel_count'].')</a></li>
                                <li><a href="'.Yii::$app->request->baseUrl.'/order/revision"><span class="glyphicon glyphicon-repeat" aria-hidden="true"></span> Revision ('.$this->params['revision_count'].')</a></li>
                                <li><a href="'.Yii::$app->request->baseUrl.'/order/completed"><i class="fa fa-trophy " aria-hidden="true"></i> Completed ('.$this->params['completed_count'].')</a></li>
                                <li><a href="'.Yii::$app->request->baseUrl.'/order/approved"><i class="fa fa-thumbs-up" aria-hidden="true"></i> Approved ('.$this->params['approved_count'].')</a></li>
                                <li><a href="'.Yii::$app->request->baseUrl.'/order/rejected"><i class="fa fa-thumbs-down " aria-hidden="true"></i> Rejected ('.$this->params['rejected_count'].')</a></li>
                              </ul>
                            </div>';
            ?>
        </div>
        <div class="col-md-4  col-md-push-8 col-sm-4  col-sm-push-8 col-xs-8">
            <?php  echo $this->render('_pending', ['model' => $searchModel]); ?>
        </div>
    </div>

    <?= \kartik\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'responsiveWrap' => false,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            //'service_id',
            [
                'attribute'=>'ordernumber',
                'width'=>'100px',
                'format' => 'raw',
                'value'=> function ($model, $key, $index, $column) {
                    return   Html::a($model->ordernumber, ['/order/view','oid'=>$model->ordernumber]);
                }
            ],
            [
                'attribute'=>'subject_id',
                'value'=>'subject.name'
            ],

            [
                'attribute'=>'deadline',
                'format' => 'raw',
                'value'=>function ($model, $key, $index, $column) {
                    $epoch = time();
                    $dt = new DateTime("@$epoch");  // convert UNIX timestamp to PHP DateTime
                    $myzone = new DateTimeZone(Yii::$app->timezone->name);
                    $dt->setTimezone($myzone);
                    $dt->format('Y-m-d H:i:s');
                    $interval = date_diff( date_create( $dt->format('Y-m-d H:i:s')), date_create($model->deadline));

                    $date_days = $interval->format('%a');
                    $date_hours = $interval->format('%r%H');
                    $date_minutes = $interval->format('%r%I');
                    if($date_days == 0) {
                        if ($interval->format('%r%I') < 0 && $interval->format('%H') == 0) {
                            return '<p style="color: red">' . $interval->format('%r%I minutes') . ' </p>';
                        }else if ($interval->format('%r%I') > 0 && $interval->format('%H') == 0) {
                            return '<p style="color: green">' . $interval->format('%r%I minutes') . ' </p>';
                        }else if($interval->format('%r%H') < 0){
                            return  '<p style="color: red">'.$interval->format('%r%H hours %I minutes' ).' </p>';
                        }else if($interval->format('%r%H') > 0){
                            return  '<p style="color: green">'.$interval->format('%r%H hours %I minutes' ).' </p>';
                        }else{
                            return '<p style="color: green">'.$interval->format('%r%H hours %I minutes' ).' </p>';
                        }

                    }else  if($date_hours == 0) {
                        if ($interval->format('%r%I') < 0 && $interval->format('%a') == 0) {
                            return '<p style="color: red">' . $interval->format('%r%I minutes') . ' </p>';
                        }else if ($interval->format('%r%I') > 0 && $interval->format('%a') == 0) {
                            return '<p style="color: green">' . $interval->format('%r%I minutes') . ' </p>';
                        }else if ($interval->format('%r%a') < 0) {
                            return '<p style="color: red">' . $interval->format('%r%a days %I minutes') . ' </p>';
                        }else if ($interval->format('%r%a') > 0) {
                            return '<p style="color: green">' . $interval->format('%r%a days %I minutes') . ' </p>';
                        }else{
                            return '<p style="color: green">'.$interval->format('%r%a days %H hours %I minutes' ).' </p>';
                        }

                    }
                    else if ($interval->format('%r%a') < 0){
                        return  '<p style="color: red">'.$interval->format('%r%a days %H hours %I minutes' ).' </p>';

                    }else{
                        return  '<p  style="color: green">'.$interval->format('%a days %H hours %I minutes' ).' </p>';
                    }

                }
            ],
            [
                'attribute'=>'type_id',
                'value'=>'type.name'
            ],
//                'created_by',
//                'written_by',
//                'edited_by',
            [
                'attribute'=>'pages_id',
                'width'=>'100px',
                'format' => 'raw',
                'value'=>function ($model, $key, $index, $column) {
                    return   '<p style="text-align: center">'.$model->pages->no_of_pages.'</p>';
                }
            ],
            //'subject_id',
            [
                'attribute'=>'amount',
                'width'=>'100px',
                'format' => 'raw',
                'value'=>function ($model, $key, $index, $column) {
                    if ($model->amount != null){
                        return   '<p>$'.$model->amount.'</p>';
                    }else{
                        return '<p>$0.00</p>';
                    }
                }
            ],
            [
                'attribute'=>'ordernumber',
                'label'=>'Reserve Now',
                'width'=>'100px',
                'format' => 'raw',
                'value'=> function ($model, $key, $index, $column) {
                    return   Html::a('Reserve', ['/order/reserve','oid'=>$model->ordernumber], ['class' => 'btn btn-primary']);
                }
            ],
            //'sources_id',
            //'language_id',
            //'pagesummary',
            //'plagreport',
            //'initialdraft',
            //'topic',
            //'instructions:ntext',
            //'qualitycheck',
            //'topwriter',
            //'phone',
            //'promocode',
            //'files',
            //'created_at',
        ],
    ]); ?>
</div>