models/Blog.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "blog".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $slug
 * @property string $created_at
 */
class Blog extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['created_at'], 'safe'],
            [['title', 'slug'], 'string', 'max' =>1000],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'slug' => 'Slug',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @inheritdoc
     * @return BlogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BlogQuery(get_called_class());
    }
}

controllers/BlogController.php
<?php

namespace app\controllers;

use Cocur\Slugify\Slugify;
use Yii;
use app\models\Blog;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BlogController implements the CRUD actions for Blog model.
 */
class BlogController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
               [
                'class' => 'yii\filters\PageCache',
                'only' => ['index', 'create','delete','view','update'],
                'duration' => 1209600,
                'variations' => [
                    \Yii::$app->language,
                    ],
                ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Blog models.
     * @return mixed
     */
    public function actionIndex()
    {
        $blogs = Blog::find()->orderBy('id DESC');
        // get the total number of articles (but do not fetch the article data yet)
        $count = $blogs->count();
        // create a pagination object with the total count
        $pagination = new Pagination(['totalCount' => $count]);
        $pagination->pageSize = 5;
        // limit the query using the pagination and retrieve the articles
        $articles = $blogs->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        return $this->render('index', [
            'blogs' => $articles,
            'pagination'=>$pagination
        ]);
    }

    /**
     * Displays a single Blog model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id, $slug)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Blog model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->user->can('admin')){
            $model = new Blog();
            if ($model->load(Yii::$app->request->post())){
                $slugify = new Slugify();
                $model->slug = $slugify->slugify($model->title);
                $model->save();
                return $this->redirect(['view', 'id' => $model->id, 'slug'=> $model->slug]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }else{
            return $this->redirect(['index']);
        }
    }

    /**
     * Updates an existing Blog model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $slug)
    {
        if (Yii::$app->user->can('admin')){
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post())) {
                $slugify = new Slugify();
                $model->slug = $slugify->slugify($model->title);
                $model->save();
                return $this->redirect(['view', 'id' => $id, 'slug'=> $model->slug]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }else{
            return $this->redirect(['index']);
        }
    }

    /**
     * Deletes an existing Blog model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($slug)
    {
        if (Yii::$app->user->can('admin')){
            $this->findModelBySlug($slug)->delete();

            return $this->redirect(['index']);
        }else{
            return $this->redirect(['index']);
        }
    }

    protected function findModelBySlug($slug)
    {
        if (($model = Blog::findOne(['slug' => $slug])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException();
        }
    }

    /**
     * Finds the Blog model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Blog the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Blog::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/blog/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Blog */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="blog-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-8">
            <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'description')->widget(\dosamigos\ckeditor\CKEditor::className(), [
                'preset' => 'custom',
                'options'=>['rows'=>18],
                'clientOptions' => [
                    'height'=>  250,
                    'toolbar' => [
                        [
                            'name' => 'row1',
                            'items' => [
                                'Source', '-',
                                'Bold', 'Italic', 'Underline', 'Strike', '-',
                                'Subscript', 'Superscript', 'RemoveFormat', '-',
                                'TextColor', 'BGColor', '-',
                                'NumberedList', 'BulletedList', '-',
                                'Outdent', 'Indent', '-', 'Blockquote', '-',
                                'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', 'list', 'indent', 'blocks', 'align', 'bidi', '-',
                                'Link', 'Unlink', 'Anchor', '-',
                                'ShowBlocks', 'Maximize',
                            ],
                        ],
                        [
                            'name' => 'row2',
                            'items' => [
                                'Image', 'Table', 'HorizontalRule', 'SpecialChar', 'Iframe', '-',
                                'NewPage', 'Print', 'Templates', '-',
                                'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-',
                                'Undo', 'Redo', '-',
                                'Find', 'SelectAll', 'Format', 'Font', 'FontSize','styles','colors', 'tools', 'others'
                            ],
                        ],
                    ],
                ],
            ]) ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/blog/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BlogSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="blog-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'slug') ?>

    <?= $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/blog/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Blog */

$this->title = 'Create Blog';
$this->params['breadcrumbs'][] = ['label' => 'Blogs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="blog-create">

        <h1><?= Html::encode($this->title) ?></h1>
        <hr>

        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>

    </div>
</div>

views/blog/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $blog app\models\Blog */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Blogs';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="blog-index">

        <h1> All <?= Html::encode($this->title) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <p>
            <?php
            if (Yii::$app->user->can('admin')){
                echo ''.Html::a('Create Blog', ['create'], ['class' => 'btn btn-success']).'';
            }
            ?>
        </p>
        <hr>
        <?php
        foreach ($blogs as $blog) {
            echo '<div class="row">
                    <div class="col-md-8">
                   <a href="'.\yii\helpers\Url::to(['blog/view', 'id'=>$blog->id, 'slug'=>$blog->slug]).'"><strong>'.$blog->title.'</strong></a> <br>
                   <div class="cut-text">'.$blog->description.'</div> <br>
                   <div><a class="btn btn-primary" href="'.\yii\helpers\Url::to(['order/create']).'">Place Order</a></div>
                  </div>
                    <div class="col-md-8">
                    <hr>
                    </div>
                  </div>
                ';
        }
        echo \yii\widgets\LinkPager::widget([
            'pagination' => $pagination,
        ]);
        ?>
    </div>
</div>

views/blog/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Blog */

$this->title = 'Update Blog: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Blogs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id, 'slug'=>$model->slug]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="container">
    <div class="blog-update">

        <h1><?= Html::encode($this->title) ?></h1>
        <hr>

        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>

    </div>
</div>

views/blog/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Blog */
$this->title = $model->title;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->description,
]);

$this->registerMetaTag([
    'name' => 'keywords',
    'content' => 'Essay Writing, Quality Essays, Academic Writing, Essay Partners, Best Essay Writers '.$this->title.', Essay Writers'
]);

$this->params['breadcrumbs'][] = ['label' => 'Blogs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="blog-view">

        <h1><?= Html::encode($this->title) ?></h1>
        <p>
            <?php
            if (Yii::$app->user->can('admin')){
                echo '<span style="margin-right: 15px">'.Html::a('Update', ['update', 'id' => $model->id, 'slug'=>$model->slug], ['class' => 'btn btn-primary']).'</span>';
                echo '<span style="margin-right: 15px">'.Html::a('Delete', ['delete', 'id' => $model->id, 'slug'=>$model->slug], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => 'Are you sure you want to delete this item?',
                            'method' => 'post',
                        ],
                    ]).'</span>';
            }
            echo ''.Html::a('Blogs', ['index'], ['class' => 'btn btn-warning']).'';
            ?>
        </p>
        <hr>
        <div class="row">
            <div class="col-md-8">
                <div style="font-size: 16px"><?= $model->description?></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 col-md-push-6">
                <a class="btn btn-lg btn-primary" href="<?= Yii::$app->request->baseUrl?>/order/create">Place Order</a>
            </div>
        </div>
    </div>

</div>